name: fit_legacy_app
description: A minimal starter Flutter app for Fit Legacy (Firebase + Auth screens)
publish_to: 'none'

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  flutter_riverpod: ^2.3.6
  flutter_svg: ^2.0.7
  freezed_annotation: ^3.1.0
  shared_preferences: ^2.1.1
  google_fonts: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  freezed: ^3.2.3
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true
  assets:
    - assets/
