name: fit_legacy_app
description: A minimal starter Flutter app for Fit Legacy (Firebase + Auth screens)
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  flutter_svg: ^2.0.7
  freezed_annotation: ^2.2.0
  json_annotation: ^4.9.0
  shared_preferences: ^2.1.1
  google_fonts: ^4.0.0
  flutter_screenutil: ^5.9.0
  gap: ^3.0.1
  auto_size_text: ^3.0.0
  flutter_animate: ^4.2.0+1
  cached_network_image: ^3.3.0
  pedometer: ^4.0.1
  permission_handler: ^11.0.1
  http: ^1.1.0
  google_generative_ai: ^0.2.1
  # Firebase dependencies
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.3
  firebase_analytics: ^11.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  freezed: ^2.3.2
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/legacito/
    - assets/images/logos/
    - assets/images/backgrounds/
